version: "3"
networks:
  archi-network:
volumes:
  archi-postgresql:
    driver: local
  archi-keycloak:
    driver: local
  archi-pgadmin:
    driver: local
services:
  postgresql:
    image: postgres:9.5
    container_name: archi-postgresql
    volumes:
      - archi-postgresql:/var/lib/postgresql/data/
    networks:
      - archi-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.2
    container_name: archi-pgadmin
    volumes:
      - archi-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - archi-network
    ports:
      - 8081:80
  keyclok:
    image: jboss/keycloak:4.8.3.Final
    container_name: archi-keyclok
    networks:
      - archi-network
    # restart: always
    ports:
      - 8082:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: Su5erAdmin
      KEYCLOAK_PASSWORD: StrongPw0rdPlea5e
    depends_on:
      - postgresql
